openapi: 3.0.2
info:
  title: oauth
  description: API to obtain OAuth 2.0 Access Token
  version: 2.0.0
paths:
  /auth/oauth/token:
    post:
      summary: Get OAuth 2.0 Access Token
      description: 'Post the following information to get an OAuth 2.0 Access Token.

        - **grant_type**: "client_credentials. APIs use Client Credentials Grant type.

        - **client_id**: *key* from the integration.

        - **client_secret**: *secret* from the integration.'
      operationId: post_client_credentiials_auth_oauth_token_post
      parameters:
      - required: true
        schema:
          title: Content-Type
          example: application/x-www-form-urlencoded
        name: content-type
        in: header
      - required: true
        schema:
          title: Accept
          example: application/json
        name: accept
        in: header
      requestBody:
        content:
          application/json:
            schema:
              title: Body
              allOf:
              - $ref: '#/components/schemas/OAuthRequest'
              example:
                grant_type: client_credentials
                client_id: jzhyhYKGkpEWAXcJ9Qd6mMkpSDMFqYUS
                client_secret: PCDNBBMx77RfdG3fCUsMnFvsEMu8y86BaN82JRpjqgBDqHbm8Hcxgj4ZKZg9gp88
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OAuthResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    OAuthRequest:
      title: OAuthRequest
      required:
      - grant_type
      - client_id
      - client_secret
      type: object
      properties:
        grant_type:
          title: Grant Type
          type: string
        client_id:
          title: Client Id
          type: string
        client_secret:
          title: Client Secret
          type: string
    OAuthResponse:
      title: OAuthResponse
      required:
      - access_token
      - token_type
      - expires_in
      - scope
      type: object
      properties:
        access_token:
          title: Access Token
          type: string
        token_type:
          title: Token Type
          type: string
        expires_in:
          title: Expires In
          type: string
        scope:
          title: Scope
          type: string
      example:
        access_token: 8b8778e5-949a-495c-a730-22809e08aa42
        token_type: bearer
        expires_in: 7199
        scope: global:manage
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            type: string
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
