get:
  summary: Get activity log of a task
  description: |-
    This endpoint is used to retrieve a list of user activities on a task..

    >## Notes
    >- (+) represents the next field and must be URL-encoded.
    >- Date format must be yyyy-MM-ddTHH:mm:ssZ (GMT).
  tags:
    - tickets
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              results:
                type: array
                items:
                  $ref: '#/components/schemas/activity'
              totalResults:
                type: integer
              pageSize:
                type: integer
              nextPage:
                type: boolean
              startDate:
                type: string
                format: date-time
              endDate:
                type: string
                format: date-time
              descendingOrder:
                type: boolean
          examples:
            example-1:
              value:
                results:
                  - activity: Task '#TASK0000001803 Update Python Version' updated by James
                    htmlLog:
                      - <div class='ActivityLogDetails'><p class='AttributeName' > New response 'time spent' added.</p><p class='AttributeName' >Time Spent (min) changed from 0 to 120</p></div>
                    createdTime: '2018-11-01T06:22:03+0000'
                    logType: TICKET
                    createdBy:
                      loginName: James.Blake
                      lastName: Blake
                      firstName: James
                      email: james.blake@myorganization.com
                      phoneNumber: 800 234-2345
                    changeLog:
                      - attribute: Time Spent (min)
                        oldValue: '0'
                        newValue: '120'
                  - activity: Task '#TASK0000001803 Update Python Version' updated by James
                    htmlLog:
                      - <div class='ActivityLogDetails'><p class='AttributeName' >estimatedHours changed from 12 hours to 13 hours </p></div>
                    createdTime: '2018-11-01T06:21:50+0000'
                    logType: TICKET
                    createdBy:
                      loginName: James.Blake
                      lastName: Blake
                      firstName: James
                      email: james.blake@myorganization.com
                      phoneNumber: 800 234-2345
                  - activity: Task '#TASK0000001803 Update Python Version' updated by James
                    htmlLog:
                      - '<div class=''ActivityLogDetails''><p class=''AttributeName'' >Priority changed from Low to High</p><p class=''AttributeName'' >startDate changed to Mon, 05 Nov 2018, 06:30 PM UTC</p></div>'
                    createdTime: '2018-11-01T06:21:43+0000'
                    logType: TICKET
                    createdBy:
                      loginName: James.Blake
                      lastName: Blake
                      firstName: James
                      email: james.blake@myorganization.com
                      phoneNumber: 800 234-2345
                    changeLog:
                      - attribute: Priority
                        oldValue: Low
                        newValue: High
                      - attribute: startDate
                        oldValue: ''
                        newValue: 'Mon, 05 Nov 2018, 06:30 PM UTC'
                  - activity: New Task "#TASK0000001803 Update Python Version" created by James
                    createdTime: '2018-11-01T06:17:59+0000'
                    logType: TICKET
                    createdBy:
                      loginName: James.Blake
                      lastName: James
                      firstName: Blake
                      email: james.blake@myorganization.com
                      phoneNumber: 800 234-2345
                totalResults: 4
                pageSize: 4
                nextPage: false
                startDate: '2018-10-29T12:26:27+0000'
                endDate: '2018-11-06T12:26:27+0000'
                descendingOrder: true
  parameters:
    - schema:
        type: string
        default: "Ticket created time\t"
      in: query
      name: startTs
      description: |-
        To retrieve activities performed on a service request within a certain duration, provide the start time and end time. startTs indicates the from date and time.
        Example: 2018-08-10T05:39:51 0000
    - schema:
        type: string
        default: Current time
      in: query
      name: endTs
      description: |-
        endTs indicates the to date and time.
        Example: 2018-08-25T10:20:15 0000
    - schema:
        type: boolean
        default: 'true'
      in: query
      name: isDescendingOrder
      description: |-
        To list the data in a descending order (high to low), provide isDescendingOrder: true, otherwise provide false. By default, data is listed in descending order.
        Example: To arrange data from 30th Oct to 1st Oct, provide isDescendingOrder: true
parameters:
  - schema:
      type: string
    in: path
    name: tenantId
    required: true
  - schema:
      type: string
    in: path
    name: taskId
    required: true
