openapi: 3.0.0
info:
  title: Agents and Gateways
  version: 2.0.0
  description: null
  contact:
    name: OpsRamp Support
    email: support@opsramp.com
    url: 'https://www.opsramp.com/about-opsramp/contact-us/'
tags:
  - name: agents-gateways
servers:
  - url: 'https://api.opsramp.com'
    description: Partner - All Others
  - url: 'https://{subdomain}.api.opsramp.com'
    description: Partner or Client custom branded sub-domain
    variables:
      subdomain:
        default: demo
        description: Custom sub-domain assigned to the client
paths:
  /api/v2/applicationservice:
    $ref: './agents-gateways/applicationservice.yaml'
  /api/v2/download/gateway/{packageName}:
    $ref: './agents-gateways/download/gateway.yaml'
  /api/v2/externalproxy:
    $ref: './agents-gateways/externalproxy.yaml'
  /api/v2/generalinfo:
    $ref: './agents-gateways/generalinfo.yaml'
  /api/v2/getntpdetails:
    $ref: './agents-gateways/getntpdetails.yaml'
  /api/v2/tenants/{tenantId}/agents/{platform}/download/{package-name}:
    $ref: './agents-gateways/tenants/agents/download.yaml'
  /api/v2/tenants/{tenantId}/agents/deployAgentsScript:
    $ref: './agents-gateways/tenants/agents/deployAgentScript.yaml'
  /api/v2/tenants/{tenantId}/agents/{platform}/info:
    $ref: './agents-gateways/tenants/agents/info.yaml'
  /api/v2/tenants/{tenantId}/agentPolicies/{policyId}/devices:
    $ref: './agents-gateways/tenants/agentPolicies/devices.yaml'
  /api/v2/tenants/{tenantId}/agentProfiles/{profileId}/devices:
    $ref: './agents-gateways/tenants/agentProfiles/devices.yaml'
  /api/v2/tenants/{tenantId}/agents/windows:
    $ref: './agents-gateways/tenants/agents/windows.yaml'
  /api/v2/registration:
    $ref: './agents-gateways/registration.yaml'
  /api/v2/proxy={action}:
    $ref: './agents-gateways/proxy.yaml'
  /api/v2/apiTokenGen:
    $ref: './agents-gateways/apiTokenGen.yaml'
  /api/v2/networksettings:
    $ref: './agents-gateways/networksettings.yaml'
  /api/v2/nginx:
    $ref: './agents-gateways/nginx.yaml'
  /api/v2/ntpmanualconfig:
    $ref: './agents-gateways/ntpmanualconfig.yaml'
  /api/v2/ntpservice:
    $ref: './agents-gateways/ntpservice.yaml'
  /api/v2/ntpupdateips:
    $ref: './agents-gateways/ntpupdateips.yaml'
  /api/v2/ntpsyncips:
    $ref: './agents-gateways/ntpsyncips.yaml'
  /api/v2/restartnetwork:
    $ref: './agents-gateways/restartnetwork.yaml'
  /api/v2/staticroute:
    $ref: './agents-gateways/staticroute.yaml'
  /api/v2/gettimezoneinfo:
    $ref: './agents-gateways/gettimezoneinfo.yaml'
  /api/v2/settimezone:
    $ref: './agents-gateways/settimezone.yaml'
  /api/v2/tenants/{tenantId}/managementProfiles/{id}/attach:
    $ref: './agents-gateways/tenants/managementProfiles/attach.yaml'
  /api/v2/tenants/{tenantId}/managementProfiles:
    $ref: './agents-gateways/tenants/managementProfiles.yaml'
  /api/v2/tenants/{tenantId}/managementProfiles/{profileId}:
    $ref: './agents-gateways/tenants/managementProfiles/profileId.yaml'
  /api/v2/tenants/{tenantId}/managementProfiles/{profileId}/detach:
    $ref: './agents-gateways/tenants/managementProfiles/detach.yaml'
  /api/v2/tenants/{tenantId}/managementProfiles/{profileId}/reconnectTunnel:
    $ref: './agents-gateways/tenants/managementProfiles/reconnectTunnel.yaml'
  /api/v2/tenants/{tenantId}/managementProfiles/search:
    $ref: './agents-gateways/tenants/managementProfiles/search.yaml'
security:
  - accessToken: []
