openapi: 3.0.0
info:
  title: OpsRamp APIs
  description: OpsRamp API Documentation
  termsOfService: https://www.opsramp.com/terms-of-use/
  contact:
    name: OpsRamp Support
    email: support@opsramp.com
    url: https://www.opsramp.com/about-opsramp/contact-us
  license:
    name: OpsRamp Master Services Agreement
    url: https://www.opsramp.com/terms-of-use/
  version: v2

tags:
  - name: auth
    description: API authentication
    externalDocs:
      url: https://docs.opsramp.com/api/authentication/

servers:
  - url: https://{tenant-name}.api.opsramp.com
    description: OpsRamp OAuth 2.0 access token API server
paths:
  /auth/oauth/token:
    post:
      operationId: auth-oauth-token
      summary: Get OAuth2 access token with client credentials
      description: 'Post the following information to get an [OAuth 2.0](https://www.oauth.com/)
        Access Token.

        - **grant_type**: "client_credentials. APIs use Client Credentials Grant type.

        - **client_id**: *key* from the integration.

        - **client_secret**: *secret* from the integration.'
      tags:
        - auth
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                client_id:
                  type: string
                  description: Client ID (key)
                client_secret:
                  type: string
                  description: Secret Key generated along with token (secret).
                grant_type:
                  type: string
                  description: Credentials of client.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  token_type:
                    type: string
                  expires_in:
                    type: string
                  scope:
                    type: string
              examples:
                example-1:
                  value:
                    access_token: 6b4a5f03-7d49-4915-9792-2d964806cbd1
                    token_type: bearer
                    expires_in: '5999'
                    scope: read write
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
              examples:
                example-1:
                  value:
                    error: unsupported_grant_type
                    error_description: 'Unsupported grant type: user_password'
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
              examples:
                example-1:
                  value:
                    error: unauthorized
                    error_description: Bad API credentials
components:
  securitySchemes:
    accessToken:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://subdomain.api.opsramp.com'
          scopes: {}
  parameters: {}
