openapi: 3.0.0
info:
  title: opsramp-automation
  version: 2.0.0
  description: API Documentation
  contact:
    name: OpsRamp Support
    email: support@opsramp.com
    url: https://www.opsramp.com/about-opsramp/contact-us/
tags:
  - name: agents-gateways
  - name: alerts
  - name: automation
  - name: components
  - name: exports
  - name: integrations
  - name: knowledge-base
  - name: metrics
  - name: monitoring
  - name: patching
  - name: resource-management
  - name: tenancy-access-controls
  - name: tickets
servers:
  - url: "https://api.opsramp.com"
    description: Partner - All Others
  - url: "https://{subdomain}.api.opsramp.com"
    description: Partner or Client custom branded sub-domain
    variables:
      subdomain:
        default: demo
        description: Custom sub-domain assigned to the client
paths:
  /auth/oauth/token:
    post:
      summary: Get OAuth2 access token with client credentials
      description: This endpoint is used to generate an access token using client credentials.
      operationId: first-response-policy-oauth2-access-token-client-creds-get/
      tags:
        - alerts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  token_type:
                    type: string
                  expires_in:
                    type: string
                  scope:
                    type: string
              examples:
                example-1:
                  value:
                    access_token: 6b4a5f03-7d49-4915-9792-2d964806cbd1
                    token_type: bearer
                    expires_in: 5999
                    scope: read write
        '400':
          description: "Bad Request\n\nFor invalid grant_type values.\t"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
              examples:
                example-1:
                  value:
                    error: unsupported_grant_type
                    error_description: 'Unsupported grant type: user_password'
        '401':
          description: |-
            Unauthorized

            For invalid/key combinations.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
              examples:
                example-1:
                  value:
                    error: unauthorized
                    error_description: Bad API credentials
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                client_id:
                  type: string
                  description: |
                    Client ID (key)
                client_secret:
                  type: string
                  description: |
                    Secret Key generated along with token (secret).
                grant_type:
                  type: string
                  description: |
                    Credentials of client.
        description: ''
      externalDocs:
        url: 'https://docs.opsramp.com/api/alerts/first-response-policy-oauth2-access-token-client-creds-get/'
  # Agents and Gateways
  /api/v2/applicationservice:
    $ref: './agents-gateways/applicationservice.yaml'
  /api/v2/download/gateway/{packageName}:
    $ref: './agents-gateways/download/gateway.yaml'
  /api/v2/externalproxy:
    $ref: './agents-gateways/externalproxy.yaml'
  /api/v2/generalinfo:
    $ref: './agents-gateways/generalinfo.yaml'
  /api/v2/getntpdetails:
    $ref: './agents-gateways/getntpdetails.yaml'
  /api/v2/tenants/{tenantId}/agents/{platform}/download/{package-name}:
    $ref: './agents-gateways/tenants/agents/download.yaml'
  /api/v2/tenants/{tenantId}/agents/deployAgentsScript:
    $ref: './agents-gateways/tenants/agents/deployAgentScript.yaml'
  /api/v2/tenants/{tenantId}/agents/{platform}/info:
    $ref: './agents-gateways/tenants/agents/info.yaml'
  /api/v2/tenants/{tenantId}/agentPolicies/{policyId}/devices:
    $ref: './agents-gateways/tenants/agentPolicies/devices.yaml'
  /api/v2/tenants/{tenantId}/agentProfiles/{profileId}/devices:
    $ref: './agents-gateways/tenants/agentProfiles/devices.yaml'
  /api/v2/tenants/{tenantId}/agents/windows:
    $ref: './agents-gateways/tenants/agents/windows.yaml'
  /api/v2/registration:
    $ref: './agents-gateways/registration.yaml'
  /api/v2/proxy={action}:
    $ref: './agents-gateways/proxy.yaml'
  /api/v2/apiTokenGen:
    $ref: './agents-gateways/apiTokenGen.yaml'
  /api/v2/networksettings:
    $ref: './agents-gateways/networksettings.yaml'
  /api/v2/nginx:
    $ref: './agents-gateways/nginx.yaml'
  /api/v2/ntpmanualconfig:
    $ref: './agents-gateways/ntpmanualconfig.yaml'
  /api/v2/ntpservice:
    $ref: './agents-gateways/ntpservice.yaml'
  /api/v2/ntpupdateips:
    $ref: './agents-gateways/ntpupdateips.yaml'
  /api/v2/ntpsyncips:
    $ref: './agents-gateways/ntpsyncips.yaml'
  /api/v2/restartnetwork:
    $ref: './agents-gateways/restartnetwork.yaml'
  /api/v2/staticroute:
    $ref: './agents-gateways/staticroute.yaml'
  /api/v2/gettimezoneinfo:
    $ref: './agents-gateways/gettimezoneinfo.yaml'
  /api/v2/settimezone:
    $ref: './agents-gateways/settimezone.yaml'
  /api/v2/tenants/{tenantId}/managementProfiles/{id}/attach:
    $ref: './agents-gateways/tenants/managementProfiles/attach.yaml'
  /api/v2/tenants/{tenantId}/managementProfiles:
    $ref: './agents-gateways/tenants/managementProfiles.yaml'
  /api/v2/tenants/{tenantId}/managementProfiles/{profileId}:
    $ref: './agents-gateways/tenants/managementProfiles/profileId.yaml'
  /api/v2/tenants/{tenantId}/managementProfiles/{profileId}/detach:
    $ref: './agents-gateways/tenants/managementProfiles/detach.yaml'
  /api/v2/tenants/{tenantId}/managementProfiles/{profileId}/reconnectTunnel:
    $ref: './agents-gateways/tenants/managementProfiles/reconnectTunnel.yaml'
  /api/v2/tenants/{tenantId}/managementProfiles/search:
    $ref: './agents-gateways/tenants/managementProfiles/search.yaml'
  # Alerts
  /api/v2/tenants/{tenantId}/policies/alertCorrelation/{policyId}/{action}:
    $ref: './alerts/tenants/policies/alertCorrelation/policyId/action.yaml'
  /api/v2/tenants/{tenantId}/rosters/search:
    $ref: './alerts/tenants/rosters/search.yaml'
  /api/v2/tenants/{tenantId}/policies/alertCorrelation:
    $ref: './alerts/tenants/policies/alertCorrelation.yaml'
  /api/v2/tenants/{tenantId}/policies/alertCorrelation/{policyId}:
    $ref: './alerts/tenants/policies/alertCorrelation/policyId.yaml'
  /api/v2/tenants/{tenantId}/agentPolicies/{policyId}/devices:
    $ref: './alerts/tenants/agentPolicies/policyId/devices.yaml'
  /api/v2/tenants/{tenantId}/alerts/{alertId}/escalations:
    $ref: './alerts/tenants/alerts/alertId/escalations.yaml'
  /api/v2/tenants/{tenantId}/escalations:
    $ref: './alerts/tenants/escalations.yaml'
  /api/v2/tenants/{tenantId}/escalations/{id}:
    $ref: './alerts/tenants/escalations/id.yaml'
  /api/v2/tenants/{tenantId}/escalations/{id}/disable:
    $ref: './alerts/tenants/escalations/id/disable.yaml'
  /api/v2/tenants/{tenantId}/escalations/{id}/enable:
    $ref: './alerts/tenants/escalations/id/enable.yaml'
  /api/v2/tenants/{tenantId}/escalations/search:
    $ref: './alerts/tenants/escalations/search.yaml'
  /api/v2/tenants/{tenantId}/alerts/{alertId}/acknowledge:
    $ref: './alerts/tenants/alerts/alertId/acknowledge.yaml'
  /api/v2/tenants/{tenantId}/alerts/{alertId}/actions/{action}:
    $ref: './alerts/tenants/alerts/alertId/actions/action.yaml'
  /api/v2/alerts/tenants/{tenantId}/alerts/event/{eventId}:
    $ref: './alerts/tenants/alerts/events/eventId.yaml'
  /api/v2/tenants/{tenantId}/alerts/{alertId}/comments:
    $ref: './alerts/tenants/alerts/alertId/comments.yaml'
  /api/v2/tenants/{tenantId}/alerts/{alertId}:
    $ref: './alerts/tenants/alerts/alertId.yaml'
  /api/v2/alertTypes:
    $ref: './alerts/alertTypes.yaml'
  /api/v2/tenants/{orgId}/users/{userId}/alertViews:
    $ref: './alerts/tenants/users/userId/alertViews.yaml'
  /api/v2/tenants/{orgId}/users/{userId}/alertViews/{viewId}:
    $ref: './alerts/tenants/users/userId/alertViews/viewId.yaml'
  /api/v2/alerts/tenants/{tenantId}/alerts/{alertId}:
    $ref: './alerts/alerts/tenants/alerts/alertId.yaml'
  /api/v2/alerts/tenants/{tenantId}/tickets/{ticketId}:
    $ref: './alerts/alerts/tenants/tickets/tickedId.yaml'
  /api/v2/tenants/{tenantId}/alerts/{alertId}/incidents/{IncidentId}/attach:
    $ref: './alerts/tenants/alerts/alertId/incidents/incidentId/attach.yaml'
  /api/v2/tenants/{tenantId}/alert:
    $ref: './alerts/tenants/alert.yaml'
  /api/v2/tenants/{tenantId}/alerts:
    $ref: './alerts/tenants/alerts.yaml'
  /api/v2/tenants/{tenantId}/alerts/{alertId}/occurrences:
    $ref: './alerts/tenants/alerts/alertId/occurrences.yaml'
  /api/v2/tenants/{tenantId}/alerts/search:
    $ref: './alerts/tenants/alerts/search.yaml'
  /api/v2/tenants/{tenantId}/alertStatusHistory/{alertId}:
    $ref: './alerts/tenants/alertStatusHistory/alertId.yaml'
  /api/v2/tenants/{tenantId}/subAlertTypes:
    $ref: './alerts/tenants/subAlertTypes.yaml'
  /api/v2/tenants/{tenantId}/alerts/{alertId}/tickets/{ticketId}/update:
    $ref: './alerts/tenants/alerts/alertId/tickets/ticketId/update.yaml'
  /api/v2/tenants/{tenantId}/policies/firstResponse:
    $ref: './alerts/tenants/policies/firstResponse.yaml'
  /api/v2/tenants/{tenantId}/policies/firstResponse/{policyId}:
    $ref: './alerts/tenants/policies/firstResponse/policyId.yaml'
  /api/v2/tenants/{tenantId}/policies/firstResponse/{policyId}/{status}:
    $ref: './alerts/tenants/policies/firstResponse/policyId/status.yaml'
  /api/v2/tenants/{tenantId}/rosters:
    $ref: './alerts/tenants/rosters.yaml'
  /api/v2/tenants/{tenantId}/rosters/{id}:
    $ref: './alerts/tenants/rosters/id.yaml'
  /api/v2/tenants/{tenantId}/scheduleMaintenances/{smId}/resources:
    $ref: './alerts/tenants/scheduleMaintenances/smId/resources.yaml'
  /api/v2/tenants/{tenantId}/scheduleMaintenances:
    $ref: './alerts/tenants/scheduleMaintenances.yaml'
  /api/v2/tenants/{tenantId}/scheduleMaintenances/{smId}/end:
    $ref: './alerts/tenants/scheduleMaintenances/smId/end.yaml'
  /api/v2/tenants/{tenantId}/scheduleMaintenances/{smId}/resources/{resourcesType}:
    $ref: './alerts/tenants/scheduleMaintenances/smId/resources/resourcesType.yaml'
  /api/v2/tenants/{tenantId}/scheduleMaintenances/{smId}/resume:
    $ref: './alerts/tenants/scheduleMaintenances/smId/resume.yaml'
  /api/v2/tenants/{tenantId}/scheduleMaintenances/search:
    $ref: './alerts/tenants/scheduleMaintenances/search.yaml'
  /api/v2/tenants/{tenantId}/scheduleMaintenances/{smId}/suspend:
    $ref: './alerts/tenants/scheduleMaintenances/smId/suspend.yaml'
  /api/v2/tenants/{tenantId}/scheduleMaintenances/{smId}:
    $ref: './alerts/tenants/scheduleMaintenances/smId.yaml'
  # Automation
  /api/v2/tenants/{tenantId}/jobs:
    $ref: './automation/tenants/jobs.yaml'
  /api/v2/tenants/{tenantId}/jobs/{id}:
    $ref: './automation/tenants/jobs/id.yaml'
  /api/v2/tenants/{tenantId}/jobs/types:
    $ref: './automation/tenants/jobs/types.yaml'
  /api/v2/tenants/{tenantId}/jobs/{id}/run:
    $ref: './automation/tenants/jobs/id/run.yaml'
  /api/v2/tenants/{tenantId}/jobs/{id}/script/run:
    $ref: './automation/tenants/jobs/id/script/run.yaml'
  /api/v2/tenants/{tenantId}/jobs/search:
    $ref: './automation/tenants/jobs/search.yaml'
  /api/v2/tenants/{tenantId}/rba/categories:
    $ref: './automation/tenants/rba/categories.yaml'
  /api/v2/tenants/{tenantId}/rba/categories/{categoryId}:
    $ref: './automation/tenants/rba/categories/categoryId.yaml'
  /api/v2/tenants/{tenantId}/rba/categories/{categoryId}/scripts:
    $ref: './automation/tenants/rba/categories/categoryId/scripts.yaml'
  /api/v2/tenants/{tenantId}/rba/scripts/{scriptId}/paginatedOutputs:
    $ref: './automation/tenants/rba/scripts/scriptId/paginatedOutputs.yaml'
  /api/v2/tenants/{tenantId}/rba/categories/{categoryId}/scripts/{scriptId}:
    $ref: './automation/tenants/rba/categories/categoryId/scripts/scriptId.yaml'
  # Exports
  /api/v2/exports/tenants/{tenantId}/create:
    $ref: './exports/tenants/create.yaml'
  # Integrations
  /api/v2/tenants/{tenantId}/integrations/activity:
    $ref: './integrations/tenants/integrations/activity.yaml'
  /api/v2/tenants/{tenantId}/policies/discovery:
    $ref: './integrations/tenants/policies/discovery.yaml'
  /api/v2/tenants/{tenantId}/policies/discovery/{discoveryId}:
    $ref: './integrations/tenants/policies/discovery/discoveryId.yaml'
  /api/v2/tenants/{tenantId}/policies/discovery/action/scan/{discoveryProfileId}:
    $ref: './integrations/tenants/policies/discovery/action/scan/discoveryProfileId.yaml'
  /api/v2/tenants/{tenantId}/policies/discovery/search:
    $ref: './integrations/tenants/policies/discovery/search.yaml'
  /api/v2/tenants/{tenantId}/integrations/install/CUSTOM:
    $ref: './integrations/tenants/integrations/install/CUSTOM.yaml'
  /api/v2/tenants/{tenantId}/integrations/available/{intgId}/emailProps/{entityType}:
    $ref: './integrations/tenants/integrations/available/intgId/emailProps/entityType.yaml'
  /api/v2/tenants/{tenantId}/integrations/installed/{installedIntgId}/inbound/authentication:
    $ref: './integrations/tenants/integrations/installed/installedIntgId/inbound/authentication.yaml'
  /api/v2/tenants/{tenantId}/integrations/installed/{installedIntgId}/mappingAttr:
    $ref: './integrations/tenants/integrations/installed/installedIntgId/mappingAttr.yaml'
  /api/v2/tenants/{tenantId}/integrations/installed/{installedIntgId}/notifier:
    $ref: './integrations/tenants/integrations/installed/installedIntgId/notifier.yaml'
  /api/v2/tenants/{tenantId}/integrations/installed/{installedIntgId}/disable:
    $ref: './integrations/tenants/integrations/installed/installedIntgId/disable.yaml'
  /api/v2/tenants/{tenantId}/integrations/installed/{installedIntgId}/enable:
    $ref: './integrations/tenants/integrations/installed/installedIntgId/enable.yaml'
  /api/v2/tenants/{tenantId}/integrations/installed/{installedIntgId}/event/{eventId}/activate:
    $ref: './integrations/tenants/integrations/installed/installedIntgId/event/eventId/activate.yaml'
  /api/v2/tenants/{tenantId}/integrations/installed/{installedIntgId}/event:
    $ref: './integrations/tenants/integrations/installed/installedIntgId/event.yaml'
  /api/v2/tenants/{tenantId}/integrations/installed/{installedIntgId}/event/{eventId}/deactivate:
    $ref: './integrations/tenants/integrations/installed/installedIntgId/event/eventId/deactivate.yaml'
  /api/v2/tenants/{tenantId}/integrations/installed/{installedIntgId}/event/{eventId}:
    $ref: './integrations/tenants/integrations/installed/installedIntgId/event/eventId.yaml'
  /api/v2//tenants/{tenantId}/integrations/installed/{installedIntgId}/events:
    $ref: './integrations/tenants/integrations/installed/installedIntgId/events.yaml'
  /api/v2//tenants/{tenantId}/integrations/events/placeHolders/{entityType}:
    $ref: './integrations/tenants/integrations/events/placeHolders/entityType.yaml'
  /api/v2/tenants/{tenantId}/integrations/installed/{installedIntgId}:
    $ref: './integrations/tenants/integrations/installed/installedIntgId.yaml'
  /api/v2/tenants/{tenantId}/integrations/available/{intgId}/mappingAttr/{entityType}:
    $ref: './integrations/tenants/integrations/available/intgId/mappingAttr/entityType.yaml'
  /api/v2/tenants/{tenantId}/integrations/available/search:
    $ref: './integrations/tenants/integrations/available/search.yaml'
  /api/v2/tenants/{tenantId}/integrations/installed/search:
    $ref: './integrations/tenants/integrations/installed/search.yaml'
  /api/v2/tenants/{tenantId}/integrations/install/EMAILINCIDENTS:
    $ref: './integrations/tenants/integrations/install/EMAILINCIDENTS.yaml'
  /api/v2/tenants/{tenantId}/integrations/install/EMAILALERTS:
    $ref: './integrations/tenants/integrations/install/EMAILALERTS.yaml'
  /api/v2/tenants/{tenantId}/integrations/install/AWS:
    $ref: './integrations/tenants/integrations/install/AWS.yaml'
  /api/v2/tenants/{tenantId}/integrations/install/AZURE:
    $ref: './integrations/tenants/integrations/install/AZURE.yaml'
  /api/v2/tenants/{tenantId}/integrations/install/GOOGLE:
    $ref: './integrations/tenants/integrations/install/GOOGLE.yaml'
  /api/v2/tenants/{tenantId}/integrations/install/{intgId}:
    $ref: './integrations/tenants/integrations/install/intgId.yaml'
  /api/v2/tenants/{tenantId}/integrations/install/OKTA:
    $ref: './integrations/tenants/integrations/install/OKTA.yaml'
