openapi: 3.0.0
info:
  title: opsramp-automation
  version: 2.0.0
  description: API Documentation
  contact:
    name: OpsRamp Support
    email: support@opsramp.com
    url: https://www.opsramp.com/about-opsramp/contact-us/

tags:
  - name: agents-gateways
    description: Example description.
    externalDocs:
      url: https://docs.opsramp.com/api/agents-gateways/
  - name: alerts
  - name: automation
  - name: components
  - name: exports
  - name: integrations
  - name: knowledge-base
  - name: metrics
  - name: monitoring
  - name: patching
  - name: resource-management
  - name: tenancy-access-controls
  - name: tickets

servers:
  - url: https://api.opsramp.com
    description: Partner - All Others
  - url: https://{subdomain}.api.opsramp.com
    description: Partner or Client custom branded sub-domain
    variables:
      subdomain:
        default: demo
        description: Custom sub-domain assigned to the client

paths:
  /auth/oauth/token:
    post:
      summary: Get OAuth2 access token with client credentials
      description: Generates an access token using client credentials.
      tags:
        - alerts
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                client_id:
                  type: string
                  description: Client ID (key)
                client_secret:
                  type: string
                  description: Secret Key generated along with token (secret).
                grant_type:
                  type: string
                  description: Credentials of client.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  token_type:
                    type: string
                  expires_in:
                    type: string
                  scope:
                    type: string
              examples:
                example-1:
                  value:
                    access_token: 6b4a5f03-7d49-4915-9792-2d964806cbd1
                    token_type: bearer
                    expires_in: '5999'
                    scope: read write
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
              examples:
                example-1:
                  value:
                    error: unsupported_grant_type
                    error_description: 'Unsupported grant type: user_password'
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
              examples:
                example-1:
                  value:
                    error: unauthorized
                    error_description: Bad API credentials
  # Agents and Gateways
  # Alerts
  # Exports
  /api/v2/exports/tenants/{tenantId}/create:
    $ref: './exports/exports-tenants-tenantid-create.yaml'
  # Integrations
  # Knowledge Base
  # Metrics
  # Monitoring
  # Patching
  # Resource Management
  # Tenancy Access Controls
  # Tickets
