paths:
  /api/v2/tenants/{tenantId}/jobs:
    post:
      summary: Create job
      description: |-
        This endpoint is used to create a job.

        ## Sample URLs
        ```
        
        ```
        ## Sample cURL
        ```
        
        ```
      operationId: automation-jobs-create-post/
      tags:
        - automation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
              examples:
                example-1:
                  value:
      requestBody:
        content:
          application/json:
            schema:
            examples:
              example-1:
      externalDocs:
        url: https://docs.opsramp.com/api/automation/automation-jobs-create-post/
    parameters:
      - schema:
          type: string
        in: path
        name: tenantId
        required: true
  /api/v2/tenants/{tenantId}/jobs/{id}:
    get:
      summary: Get job
      description: |-
        This endpoint is used to retrieve the job details.

        ## Sample URLs
        ```
        
        ```
        ## Sample cURL
        ```
        
        ```
      operationId: automation-jobs-get-job-get/
      tags:
        - automation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
              examples:
                example-1:
                  value:
      requestBody:
        content:
          application/json:
            schema:
            examples:
              example-1:
      externalDocs:
        url: https://docs.opsramp.com/api/automation/automation-jobs-get-job-get/
    delete:
      summary: Delete job
      description: |-
        This endpoint is used to delete a job.

        ## Sample URLs
        ```
        
        ```
        ## Sample cURL
        ```
        
        ```
      operationId: automation-jobs-job-delete/
      tags:
        - automation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
              examples:
                example-1:
                  value:
      requestBody:
        content:
          application/json:
            schema:
            examples:
              example-1:
      externalDocs:
        url: https://docs.opsramp.com/api/automation/automation-jobs-job-delete/
    post:
      summary: Update job
      description: |-
        This endpoint is used to update a job.

        ## Sample URLs
        ```
        
        ```
        ## Sample cURL
        ```
        
        ```
      operationId: automation-jobs-update-post/
      tags:
        - automation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
              examples:
                example-1:
                  value:
      requestBody:
        content:
          application/json:
            schema:
            examples:
              example-1:
      externalDocs:
        url: https://docs.opsramp.com/api/automation/automation-jobs-update-post/
    parameters:
      - schema:
          type: string
        in: path
        name: tenantId
        required: true
      - schema:
          type: string
        in: path
        name: id
        required: true
  /api/v2/tenants/{tenantId}/jobs/types:
    get:
      summary: Get job types
      description: |-
        This endpoint is used to retrieve the list of job types.

        ## Sample URLs
        ```
        
        ```
        ## Sample cURL
        ```
        
        ```
      operationId: automation-jobs-job-types-get/
      tags:
        - automation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
              examples:
                example-1:
                  value:
      requestBody:
        content:
          application/json:
            schema:
            examples:
              example-1:
      externalDocs:
        url: https://docs.opsramp.com/api/automation/automation-jobs-job-types-get/
    parameters:
      - schema:
          type: string
        in: path
        name: tenantId
        required: true
  /api/v2/tenants/{tenantId}/jobs/{id}/run:
    get:
      summary: Run job
      description: |-
        This endpoint is used to run a scheduled job.

        ## Sample URLs
        ```
        
        ```
        ## Sample cURL
        ```
        
        ```
      operationId: automation-jobs-run-job-get/
      tags:
        - automation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
              examples:
                example-1:
                  value:
      requestBody:
        content:
          application/json:
            schema:
            examples:
              example-1:
      externalDocs:
        url: https://docs.opsramp.com/api/automation/automation-jobs-run-job-get/
    parameters:
      - schema:
          type: string
        in: path
        name: tenantId
        required: true
      - schema:
          type: string
        in: path
        name: id
        required: true
  /api/v2/tenants/{tenantId}/jobs/{id}/script/run:
    post:
      summary: Run script
      description: |-
        This endpoint is used to run a script.

        ## Sample URLs
        ```
        
        ```
        ## Sample cURL
        ```
        
        ```
      operationId: automation-jobs-run-script-post/
      tags:
        - automation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
              examples:
                example-1:
                  value:
      requestBody:
        content:
          application/json:
            schema:
            examples:
              example-1:
      externalDocs:
        url: https://docs.opsramp.com/api/automation/automation-jobs-run-script-post/
    parameters:
      - schema:
          type: string
        in: path
        name: tenantId
        required: true
      - schema:
          type: string
        in: path
        name: id
        required: true
  /api/v2/tenants/{tenantId}/jobs/searc:
    get:
      summary: Search jobs
      description: |-
        This endpoint is used to fetch the list of jobs defined by a tenant.

        ## Sample URLs
        ```
        
        ```
        ## Sample cURL
        ```
        
        ```
      operationId: automation-jobs-search-jobs-get/
      tags:
        - automation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
              examples:
                example-1:
                  value:
      requestBody:
        content:
          application/json:
            schema:
            examples:
              example-1:
      externalDocs:
        url: https://docs.opsramp.com/api/automation/automation-jobs-search-jobs-get/
    parameters:
      - schema:
          type: string
        in: path
        name: tenantId
        required: true
  /api/v2/tenants/{tenantId}/rba/categories:
    post:
      summary: Create RBA category
      description: |-
        This endpoint is used to create an RBA category.

        ## Sample URLs
        ```
        
        ```
        ## Sample cURL
        ```
        
        ```
      operationId: rba-categories-create-post/
      tags:
        - automation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
              examples:
                example-1:
                  value:
      requestBody:
        content:
          application/json:
            schema:
            examples:
              example-1:
      externalDocs:
        url: https://docs.opsramp.com/api/automation/rba-categories-create-post/
    get:
      summary: Get RBA categories
      description: |-
        This endpoint is used to retrieve list of RBA categories.

        ## Sample URLs
        ```
        
        ```
        ## Sample cURL
        ```
        
        ```
      operationId: rba-categories-get/
      tags:
        - automation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
              examples:
                example-1:
                  value:
      requestBody:
        content:
          application/json:
            schema:
            examples:
              example-1:
      externalDocs:
        url: https://docs.opsramp.com/api/automation/rba-categories-get/
    put:
      summary: Update an RBA category
      description: |-
        This endpoint is used to update an RBA category.

        ## Sample URLs
        ```
        
        ```
        ## Sample cURL
        ```
        
        ```
      operationId: rba-categories-update-put/
      tags:
        - automation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
              examples:
                example-1:
                  value:
      requestBody:
        content:
          application/json:
            schema:
            examples:
              example-1:
      externalDocs:
        url: https://docs.opsramp.com/api/automation/rba-categories-update-put/
    parameters:
      - schema:
          type: string
        in: path
        name: tenantId
        required: true
  /api/v2/tenants/{tenantId}/rba/categories/{categoryId}:
    delete:
      summary: Delete an RBA category
      description: |-
        This endpoint is used to delete an RBA category.

        ## Sample URLs
        ```
        
        ```
        ## Sample cURL
        ```
        
        ```
      operationId: rba-categories-delete/
      tags:
        - automation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
              examples:
                example-1:
                  value:
      requestBody:
        content:
          application/json:
            schema:
            examples:
              example-1:
      externalDocs:
        url: https://docs.opsramp.com/api/automation/rba-categories-delete/
    parameters:
      - schema:
          type: string
        in: path
        name: tenantId
        required: true
      - schema:
          type: string
        in: path
        name: categoryId
        required: true
  /api/v2/tenants/{tenantId}/rba/categories/{categoryId}/scripts:
    post:
      summary: Create script
      description: |-
        This endpoint is used to create a script.

        ## Sample URLs
        ```
        
        ```
        ## Sample cURL
        ```
        
        ```
      operationId: rba-scripts-create-post/
      tags:
        - automation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
              examples:
                example-1:
                  value:
      requestBody:
        content:
          application/json:
            schema:
            examples:
              example-1:
      externalDocs:
        url: https://docs.opsramp.com/api/automation/rba-scripts-create-post/
    delete:
      summary: Delete script
      description: |-
        This endpoint is used to delete a script.

        ## Sample URLs
        ```
        
        ```
        ## Sample cURL
        ```
        
        ```
      operationId: rba-scripts-delete/
      tags:
        - automation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
              examples:
                example-1:
                  value:
      requestBody:
        content:
          application/json:
            schema:
            examples:
              example-1:
      externalDocs:
        url: https://docs.opsramp.com/api/automation/rba-scripts-delete/
    get:
      summary: Get scripts
      description: |-
        This endpoint is used to retrieve the list of scripts within a category.

        ## Sample URLs
        ```
        
        ```
        ## Sample cURL
        ```
        
        ```
      operationId: rba-scripts-scripts-get/
      tags:
        - automation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
              examples:
                example-1:
                  value:
      requestBody:
        content:
          application/json:
            schema:
            examples:
              example-1:
      externalDocs:
        url: https://docs.opsramp.com/api/automation/rba-scripts-scripts-get/
    parameters:
      - schema:
          type: string
        in: path
        name: tenantId
        required: true
      - schema:
          type: string
        in: path
        name: categoryId
        required: true
  /api/v2/tenants/{tenantId}/rba/scripts/{scriptId}/paginatedOutputs:
    get:
      summary: Get output logs
      description: |-
        This endpoint is used to retrieve paginated output logs of a script.

        ## Sample URLs
        ```
        
        ```
        ## Sample cURL
        ```
        
        ```
      operationId: rba-scripts-output-logs-get/
      tags:
        - automation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
              examples:
                example-1:
                  value:
      requestBody:
        content:
          application/json:
            schema:
            examples:
              example-1:
      externalDocs:
        url: https://docs.opsramp.com/api/automation/rba-scripts-output-logs-get/
    parameters:
      - schema:
          type: string
        in: path
        name: tenantId
        required: true
      - schema:
          type: string
        in: path
        name: scriptId
        required: true
  /api/v2/tenants/{tenantId}/rba/categories/{categoryId}/scripts/{scriptId}:
    get:
      summary: Get script
      description: |-
        This endpoint is used to retrieve details of the script.

        ## Sample URLs
        ```
        
        ```
        ## Sample cURL
        ```
        
        ```
      operationId: rba-scripts-script-get/
      tags:
        - automation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
              examples:
                example-1:
                  value:
      requestBody:
        content:
          application/json:
            schema:
            examples:
              example-1:
      externalDocs:
        url: https://docs.opsramp.com/api/automation/rba-scripts-script-get/
    post:
      summary: Update script
      description: |-
        This endpoint is used to update a script.

        ## Sample URLs
        ```
        
        ```
        ## Sample cURL
        ```
        
        ```
      operationId: rba-scripts-update-post/
      tags:
        - automation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
              examples:
                example-1:
                  value:
      requestBody:
        content:
          application/json:
            schema:
            examples:
              example-1:
      externalDocs:
        url: https://docs.opsramp.com/api/automation/rba-scripts-update-post/
    parameters:
      - schema:
          type: string
        in: path
        name: tenantId
        required: true
      - schema:
          type: string
        in: path
        name: categoryId
        required: true
      - schema:
          type: string
        in: path
        name: scriptId
        required: true
