summary: Run patch configuration
description: Runs a patch configuration.
post:
  tags:
    - patching
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            reason:
              type: string
              description: |
                Reason to run the patch configuration
          required:
            - reason
        examples:
          example-1:
            value:
              reason: To run patch config on demand
  responses:
    '200':
      description: OK
parameters:
  - $ref: '../components-global.yaml#/components/parameters/tenantId'
  - schema:
      type: string
    in: path
    name: id
    required: true
