post:
  summary: Activate or deactivate patch baseline
  description: This endpoint is used to activate or deactivate a patch baseline.
  tags:
    - patching
  responses:
    '200':
      description: OK
parameters:
  - schema:
      type: string
    in: path
    name: tenantId
    required: true
  - schema:
      type: string
    in: path
    name: baselineId
    required: true
  - schema:
      type: string
    in: path
    name: action
    required: true
