post:
  summary: Enable or disable alert correlation policy
  tags:
    - alerts
  description: 'This endpoint is used to enable, disable, and create an observed mode on an alert correlation policy.'
  responses:
    '200':
      description: OK
parameters:
  - schema:
      type: string
    name: tenantId
    in: path
    required: true
  - schema:
      type: string
    name: policyId
    in: path
    required: true
  - schema:
      type: string
      enum:
        - enable
        - disable
        - observed
    name: action
    in: path
    required: true
