post:
  summary: Assign or unassign devices from patch compliance
  description: This endpoint is used to assign or unassign devices from a patch compliance.
  tags:
    - patching
  responses:
    '200':
      description: OK
parameters:
  - schema:
      type: string
    in: path
    name: tenantId
    required: true
  - schema:
      type: string
    in: path
    name: complianceId
    required: true
  - schema:
      type: string
    in: path
    name: deviceId
    required: true
  - schema:
      type: string
    in: path
    name: action
    required: true
