openapi: 3.0.0
info:
  title: opsramp
  version: 2.0.0
  description: OpsRamp API Documentation
  contact:
    name: OpsRamp Support
    email: support@opsramp.com
    url: https://www.opsramp.com/about-opsramp/contact-us
servers:
  url: https://{subdomain}.api.opsramp.com
  description: OpsRamp API URL
security:
  type: oauth2
  description: OAuth2 security using flow client_credentials
  flows:
    clientCredentials:
      tokenUrl: https://{subdomain}.api.opsramp.com/auth/oauth/token
