openapi: 3.0.2
info:
  title: SPEC_NAME
  description: Live mock API endpoints
  version: '1.0'
paths:
  /api/v2/auth/oauth/token:
    post:
      summary: Post Client Credentiials
      operationId: post_client_credentiials_api_v2_auth_oauth_token_post
      parameters:
      - required: false
        schema:
          title: Content-Type
          type: string
          default: application/x-www-form-urlencoded
        name: content-type
        in: header
      - required: false
        schema:
          title: Accept
          type: string
          default: application/json
        name: accept
        in: header
      requestBody:
        content:
          application/json:
            schema:
              title: Oauthaccesstokenrequestbody
              allOf:
              - $ref: '#/components/schemas/OAuthAccessTokenRequestBody'
              example:
                grant_type: client_credentials
                client_id: jzhyhYKGkpEWAXcJ9Qd6mMkpSDMFqYUS
                client_secret: PCDNBBMx77RfdG3fCUsMnFvsEMu8y86BaN82JRpjqgBDqHbm8Hcxgj4ZKZg9gp88
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    OAuthAccessTokenRequestBody:
      title: OAuthAccessTokenRequestBody
      required:
      - grant_type
      - client_id
      - client_secret
      type: object
      properties:
        grant_type:
          title: Grant Type
          type: string
        client_id:
          title: Client Id
          type: string
        client_secret:
          title: Client Secret
          type: string
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            type: string
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
