openapi: 3.0.2
info:
  title: OpsHub API Explorer
  description: Live mock OpsHub API endpointts
  version: '1.0'
paths:
  /publishers/:
    post:
      summary: Create Publisher
      operationId: create_publisher_publishers__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Publisher'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Publisher'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /apps/:
    get:
      summary: Get Apps
      operationId: get_apps_apps__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Get Apps Apps  Get
                type: array
                items:
                  $ref: '#/components/schemas/App'
    post:
      summary: Create App
      operationId: create_app_apps__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/App'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/App'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /apps/{appId}:
    get:
      summary: Get App
      operationId: get_app_apps__appId__get
      parameters:
      - required: true
        schema:
          title: Appid
          type: string
          format: uuid
        name: appId
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/App'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /app-versions/:
    get:
      summary: Get App Versions
      operationId: get_app_versions_app_versions__get
      parameters:
      - required: false
        schema:
          title: Appid
          type: string
          format: uuid
        name: appId
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Get App Versions App Versions  Get
                type: array
                items:
                  $ref: '#/components/schemas/AppVersion'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      summary: Create App Version
      operationId: create_app_version_app_versions__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppVersion'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppVersion'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /app-versions/{appVersionId}:
    get:
      summary: Get App Version
      operationId: get_app_version_app_versions__appVersionId__get
      parameters:
      - required: true
        schema:
          title: Appversionid
          type: string
          format: uuid
        name: appVersionId
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppVersion'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    App:
      title: App
      required:
      - publisherId
      - name
      - description
      - type
      type: object
      properties:
        appId:
          title: Appid
          type: string
          format: uuid
        publisherId:
          title: Publisherid
          type: string
          format: uuid
        name:
          title: Name
          type: string
        description:
          title: Description
          type: string
        type:
          $ref: '#/components/schemas/AppTypes'
    AppTypes:
      title: AppTypes
      enum:
      - discovery_monitoring
      - analytics
      type: string
      description: An enumeration.
    AppVersion:
      title: AppVersion
      required:
      - appId
      - version
      - description
      - imageDigest
      - manifest
      type: object
      properties:
        appVersionId:
          title: Appversionid
          type: string
          format: uuid
        appId:
          title: Appid
          type: string
          format: uuid
        version:
          title: Version
          pattern: ^[0-9]+\.[0-9]+\.[0-9]+$
          type: string
        description:
          title: Description
          type: string
        imageDigest:
          title: Imagedigest
          type: string
        manifest:
          title: Manifest
          type: string
        state:
          allOf:
          - $ref: '#/components/schemas/AppVersionStates'
          default: regsitered
    AppVersionStates:
      title: AppVersionStates
      enum:
      - regsitered
      - in_test
      - in_review
      - rejected
      - published
      - end_of_life
      - decommissioned
      type: string
      description: An enumeration.
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    Publisher:
      title: Publisher
      required:
      - name
      - description
      type: object
      properties:
        publisherId:
          title: Publisherid
          type: string
          format: uuid
        name:
          title: Name
          type: string
        description:
          title: Description
          type: string
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            type: string
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
