summary: Specifies gateway network settings
description: Specifies the network settings on the gateway.
post:
  tags:
    - agents-gateways
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              Success:
                type: string
          examples:
            example-1:
              value:
                Success: Successfully updated network configuration.
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            hostname:
              type: string
              description: Host name for the gateway.
            domainname:
              type: string
              description: Domain name for the gateway.
            interface:
              type: string
              description: Interface for the gateway.
            static_IP:
              type: string
              description: |-
                If true, static IP is used instead of the (default) DHCP IP address.
                If false, IP address, subnet, gatewayIP, and dnsArray parameters are not required.
            ipaddr:
              type: string
              description: |-
                Static IP (instead of DHCP).
                Note: If static_IP is false, IP address, subnet, gatewayIP, and dnsArray parameters are not required.
            subnet:
              type: string
              description: |-
                Subnet for the gateway.
                Note: If static_IP is false, IP address, subnet, gatewayIP, and dnsArray parameters are not required.
            gateway:
              type: string
              description: "\tDefault gateway IP address.\nNote: If static_IP is false, IP address, subnet, gatewayIP, and dnsArray parameters are not required."
            dnsArray:
              type: string
              description: |-
                DNS entries for the gateway.
                Note: If static_IP is false, IP address, subnet, gatewayIP, and dnsArray parameters are not required.
          required:
            - hostname
            - domainname
            - interface
            - static_IP
            - ipaddr
            - subnet
            - gateway
            - dnsArray
        examples:
          example-1:
            value:
              hostname: <hostname>
              domainname: <domainname>
              interface: <interface>
              static_IP: <True/False>
              ipaddr: <IP Address>
              subnet: <subnet>
              gateway: <Default Gateway>
              dnsArray: '<xxx,xxx>'
