summary: Manually set gateway NTP date and time
description: Manually sets the NTP date and time on the gateway.
post:
  tags:
    - agents-gateways
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              Success:
                type: string
          examples:
            example-1:
              value:
                Success: Successfully updated time and date
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            date:
              type: string
              description: Date (MM-DD-YYYY)
            hour:
              type: string
              description: Hours (0-23)
            min:
              type: string
              description: Minutes (0-59)
            sec:
              type: string
              description: Seconds (0-59)
          required:
            - date
            - hour
            - min
            - sec
        examples:
          example-1:
            value:
              date: 06-21-2020
              hour: '8'
              min: '15'
              sec: '00'
