name = "OpsRamp"
license = "Commercial"
description = "Technical documentation website for OpsRamp"
homepage = "http://docs-internal.opsramp.com.s3-website-us-east-1.amazonaws.com/api/"
tags = []
features = []
min_version = 0.68
