get:
  summary: Download task response attachment
  description: This endpoint is used to download the response attachment attached to a task.
  tags:
    - tickets
  responses:
    '200':
      description: OK
      content:
        text/plain:
          schema:
            type: string
parameters:
  - $ref: '../components-global.yaml#/components/parameters/tenantId'
  - schema:
      type: string
    in: path
    name: taskId
    required: true
  - schema:
      type: string
    in: path
    name: responseId
    required: true
  - schema:
      type: string
    in: path
    name: resourceId
    required: true
