summary: Get resource applications
description: This endpoint is used to retrieve the list of applications running on a resource.
get:
  tags:
    - resource-management
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                vendor:
                  type: string
                version:
                  type: string
                installedDate:
                  type: string
                  format: date-time
                createdDate:
                  type: string
                  format: date-time
                modifiedDate:
                  type: string
                  format: date-time
          examples:
            example-1:
              value:
                - id: 538
                  name: Google Chrome
                  vendor: Google Inc.
                  version: 51.0.2704.63
                  installedDate: '2016-05-27T00:00:00+0000'
                  createdDate: '2016-05-30T10:13:27+0000'
                  modifiedDate: '2016-06-09T07:58:25+0000'
                - id: 539
                  name: Internet Explorer
                  vendor: Microsoft Corporation
                  version: 8.0.7600.16385
                  createdDate: '2016-05-30T10:13:27+0000'
                  modifiedDate: '2016-06-09T07:58:25+0000'
                - id: 540
                  name: Microsoft .NET Framework 4 Client Profile
                  vendor: Microsoft Corporation
                  version: 4.0.30319
                  createdDate: '2016-05-30T10:13:27+0000'
                  modifiedDate: '2016-06-09T07:58:25+0000'
                - id: 541
                  name: Microsoft Visual C++ 2012 Redistributable (x86) - 11.0.61030
                  vendor: Microsoft Corporation
                  version: 11.0.61030.0
                  createdDate: '2016-05-30T10:13:27+0000'
                  modifiedDate: '2016-06-09T07:58:25+0000'
                - id: 542
                  name: Oracle VM VirtualBox Guest Additions 5.0.20
                  vendor: Oracle Corporation
                  version: 5.0.20.0
                  createdDate: '2016-05-30T10:13:27+0000'
                  modifiedDate: '2016-06-09T07:58:25+0000'
                - id: 545
                  name: Microsoft .NET Framework 3.5 SP1
                  vendor: Microsoft Corporation
                  version: 3.5.30729
                  installedDate: '2016-01-01T00:00:00+0000'
                  createdDate: '2016-07-24T10:30:18+0000'
                  modifiedDate: '2016-09-07T07:27:42+0000'
parameters:
  - $ref: '../components-global.yaml#/components/parameters/tenantId'
  - schema:
      type: string
    in: path
    name: resourceId
    required: true
