summary: Change WSUS settings
description: The endpoint to assign agent policy for resources.
post:
  tags:
    - resource-management
  requestBody:
    content:
      application/json:
        schema:
          type: array
          items:
            type: object
            properties:
              entityId:
                type: string
              entityType:
                type: string
        examples:
          example-1:
            value:
              - entityId: '717'
                entityType: SITE
              - entityId: DGP-437315a3-0931-4165-b960-10e06642e942
                entityType: DEVICE_GROUP
              - entityId: 123237d7-9854-454d-ae97-7ad007efa486
                entityType: DEVICE
  responses:
    '200':
      description: OK
parameters:
  - $ref: '../components-global.yaml#/components/parameters/tenantId'
  - schema:
      type: string
    in: path
    name: action
    required: true
