post:
  summary: Assign or unassign a baseline from patch compliance
  description: This endpoint is used to assign or unassign a patch baseline attached to a patch compliance check.
  tags:
    - patching
  responses:
    '200':
      description: OK
parameters:
  - schema:
      type: string
    in: path
    name: tenantId
    required: true
  - schema:
      type: string
    in: path
    name: complianceId
    required: true
  - schema:
      type: string
    in: path
    name: baselineId
    required: true
  - schema:
      type: string
    in: path
    name: action
    required: true
