name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: 'Trigger Site Rebuild'
    runs-on: ubuntu-latest
    steps:
      - name: 'Rebuild Production'
        uses: indiesdev/curl@v1
        with:
          url: https://api.buddy.works/workspaces/opsramp/projects/docs/pipelines/233675/executions
          method: 'POST'
          accept: 200,201,204
          headers: '{ "Content-type": "application/json" }'
          body: '{ "comment": "Triggered by GitHub push" }'
          timeout: 2000
          bearer-token: ${{ secrets.buddy_token }}
          is_debug: false
      - name: 'Rebuild Internal'
        uses: indiesdev/curl@v1
        with:
          url: https://api.buddy.works/workspaces/opsramp/projects/docs/pipelines/318801/executions
          method: 'POST'
          accept: 200,201,204
          headers: '{ "Content-type": "application/json" }'
          body: '{ "comment": "Triggered by GitHub push" }'
          timeout: 2000
          bearer-token: ${{ secrets.buddy_token }}
          is_debug: false
